version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastdistraction/about-me-react-ts
    ports:
      - "81:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fastdistraction/comments-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/comments

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: